// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// You can recreate the all IDs...
//By searching on youtube "-----how to configure firebase in flutter from terminal----" and i hope you understand it.
// There are few commands that will configure the "----firebase_options.dart----" file for you.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '------Your Api Key For Android------',
    appId: 'Your App ID',
    messagingSenderId: '',
    projectId: 'Your project ID',
    databaseURL: 'Database URL',
    storageBucket: 'Your Storage Bucket ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: '------Your Api Key For IOS------',
      appId: 'Your App ID',
      messagingSenderId: '',
      projectId: 'Your project ID',
      databaseURL: 'Database URL',
      storageBucket: 'Your Storage Bucket ');

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '------Your Api Key For Web------',
    appId: 'Your App ID',
    messagingSenderId: '',
    projectId: 'Your project ID',
    databaseURL: 'Database URL',
    storageBucket: 'Your Storage Bucket ',
    authDomain: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '------Your Api Key For MacOS------',
    appId: 'Your App ID',
    messagingSenderId: '',
    projectId: 'Your project ID',
    databaseURL: 'Database URL',
    storageBucket: 'Your Storage Bucket ',
    authDomain: '',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '------Your Api Key For Windows------',
    appId: 'Your App ID',
    messagingSenderId: '',
    projectId: 'Your project ID',
    databaseURL: 'Database URL',
    storageBucket: 'Your Storage Bucket ',
    authDomain: '',
  );
}
